SmartParking/urls.py
from django.urls import path
from . import views

app_name = 'SmartParking'

urlpatterns = [
    path('',views.home, name='home'),
    # path('signout',views.signout,name='signout'),
    # path('signup/',views.signup,name='signup'),
    path('signin/',views.signin,name='signin'),
    path('detail/', views.detail,name='detail'),
    # path('parking_lot_state/', views.parking_lot_state, name='parking_lot_state'),
    # path('free_spaces/', views.free_spaces, name='free_spaces'),
]

SmartParking/models.py
from django.db import models

# Create your models here.

SmartParking/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User, auth
from django.db.models import Q
from SmartParking.models import *
import cv2
import pandas as pd
import numpy as np
from ultralytics import YOLO
import time


# Create your views here.

def home(request):
    return render(request,'SmartParking/home.html')

model=YOLO('yolov8s.pt')

def RGB(event, x, y, flags, param):
    if event == cv2.EVENT_MOUSEMOVE :  
        colorsBGR = [x, y]
        print(colorsBGR)

def parking_lot_state(request):
    cap=cv2.VideoCapture('video_2023-06-09_12-16-22.mp4')
    my_file = open("coco.txt", "r")
    data = my_file.read()
    class_list = data.split("\n")

    area1=[(270,111),(284,119),(349,103),(331,97)]
    area2=[(285,121),(301,132),(368,111),(354,106)]
    count = 0
    while True:    
        ret,frame = cap.read()
        count += 1
        if count % 15 != 0:
            continue
        if not ret:
            break
        frame=cv2.resize(frame,(1020,500))

        results=model.predict(frame)
        a=results[0].boxes.data
        px=pd.DataFrame(a).astype("float")
        list1=[]
        list2=[]

        for index,row in px.iterrows():
            x1=int(row[0])
            y1=int(row[1])
            x2=int(row[2])
            y2=int(row[3])
            d=int(row[5])
            c=class_list[d]
            if 'car' in c:
                cx=int(x1+x2)//2
                cy=int(y1+y2)//2
                results1=cv2.pointPolygonTest(np.array(area1,np.int32),((cx,cy)),False)
                if results1>=0:
                   cv2.circle(frame,(cx,cy),3,(0,0,255),-1)
                   list1.append(c)
                   cv2.putText(frame,str(c),(x1,y1),cv2.FONT_HERSHEY_COMPLEX,0.5,(255,255,255),1)
                results2=cv2.pointPolygonTest(np.array(area2,np.int32),((cx,cy)),False)
                if results2>=0:
                   cv2.circle(frame,(cx,cy),3,(0,0,255),-1)
                   list2.append(c)
        a1=(len(list1))
        a2=(len(list2)) 
        o=(a1+a2)
        space=(10-o)
        if a1==1:
            cv2.putText(frame,str('1'),(265,115),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,255),1)
        else:
            cv2.polylines(frame,[np.array(area1,np.int32)],True,(0,255,0),2)
            cv2.putText(frame,str('1'),(265,115),cv2.FONT_HERSHEY_COMPLEX,0.5,(255,255,255),1)
        if a2==1:
            cv2.putText(frame,str('2'),(280,129),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,255),1)
        else:
            cv2.polylines(frame,[np.array(area2,np.int32)],True,(0,255,0),2)
            cv2.putText(frame,str('2'),(280,129),cv2.FONT_HERSHEY_COMPLEX,0.5,(255,255,255),1)

        text = 'FREE: ' + str(space) + '/10'
        cv2.putText(frame,text,(23,30),cv2.FONT_HERSHEY_PLAIN,3,(0,255,0),2)

        # Return the number of free spaces as a plain text response
        response = HttpResponse(str(space), content_type='text/plain')
        return response
    print(response)

    cap.release()
    cv2.destroyAllWindows()



model = YOLO('yolov8s.pt')

def detail(request):
    cap = cv2.VideoCapture('video_2023-06-09_12-16-22.mp4')
    my_file = open("coco.txt", "r")
    data = my_file.read()
    class_list = data.split("\n")
    area1 = [(270, 111), (284, 119), (349, 103), (331, 97)]
    area2 = [(285, 121), (301, 132), (368, 111), (354, 106)]
    count = 0
    spaces = []
    # print(spaces)

    while True:
        ret, frame = cap.read()
        count += 1
        if count % 15 != 0:
            continue
        if not ret:
            break
        frame = cv2.resize(frame, (1020, 500))

        results = model.predict(frame)
        a = results[0].boxes.data
        px = pd.DataFrame(a).astype("float")
        list1 = []
        list2 = []

        for index, row in px.iterrows():
            x1 = int(row[0])
            y1 = int(row[1])
            x2 = int(row[2])
            y2 = int(row[3])
            d = int(row[5])
            c = class_list[d]
            if 'car' in c:
                cx = int(x1 + x2) // 2
                cy = int(y1 + y2) // 2
                results1 = cv2.pointPolygonTest(np.array(area1, np.int32), ((cx, cy)), False)
                if results1 >= 0:
                    cv2.circle(frame, (cx, cy), 3, (0, 0, 255), -1)
                    list1.append(c)
                    cv2.putText(frame, str(c), (x1, y1), cv2.FONT_HERSHEY_COMPLEX, 0.5, (255, 255, 255), 1)
                results2 = cv2.pointPolygonTest(np.array(area2, np.int32), ((cx, cy)), False)
                if results2 >= 0:
                    cv2.circle(frame, (cx, cy), 3, (0, 0, 255), -1)
                    list2.append(c)
        a1 = len(list1)
        a2 = len(list2)
        o = (a1 + a2)
        space = (10 - o)
        spaces.append(space)
        if a1 == 1:
            cv2.putText(frame, str('1'), (265, 115), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255), 1)
        else:
            cv2.polylines(frame, [np.array(area1, np.int32)], True, (0, 255, 0), 2)
            cv2.putText(frame, str('1'), (265, 115), cv2.FONT_HERSHEY_COMPLEX, 0.5, (255, 255, 255), 1)
        if a2 == 1:
            cv2.putText(frame, str('2'), (280, 129), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255), 1)
        else:
            cv2.polylines(frame, [np.array(area2, np.int32)], True, (0, 255, 0), 2)
            cv2.putText(frame, str('2'), (280, 129), cv2.FONT_HERSHEY_COMPLEX, 0.5, (255, 255, 255), 1)

        text = 'FREE: ' + str(space) + '/10'
        cv2.putText(frame, text, (23, 30), cv2.FONT_HERSHEY_PLAIN, 3, (0, 255, 0), 2)

        cv2.imshow("RGB", frame)

        if cv2.waitKey(100) & 0xFF == ord('d'):
            break

    cap.release()
    cv2.destroyAllWindows()

    context = {
        'spaces': spaces
    }
    return render(request, 'SmartParking/detail.html', context)


# def detail(request):
#     return render(request,'SmartParking/detail.html')
# def signup(request):
#     if request.method == 'POST':
#         # first_name = request.POST['first_name']
#         # last_name = request.POST['last_name']
#         username = request.POST['username']
#         email = request.POST['email']
#         password = request.POST['password']
#         password2 = request.POST['password2']

#         if password == password2:
#             if User.objects.filter(email=email).exists():
#                 messages.info(request, 'Email Already Used') 
#                 return redirect('')
#             elif User.objects.filter(username=username).exists():
#                 messages.info(request,'Username Already taken')
#                 return redirect('')
#             else:
#                 user = User.objects.create_user(username=username, email=email, password=password)
#                 user.save()

#                 # log user in and direct to settings page later 
#                 user_login = auth.authenticate(username=username, password=password)
#                 auth.login(request,user_login)

#                 # New profile for new User 
#                 user_model = User.objects.get(username=username)
#                 # new_profile = UserProfile.objects.create(user=user_model)
#                 # new_profile.save()
#                 # return redirect('Post:settings')
#         else:
#             messages.info(request,'Password Not Matching')
#             return redirect('Users:signup')
   
#     else:
#         return render(request, 'Users/signup.html')
#     context = {}
#     return render(request,'Users/signup.html',context)
    
def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('SmartParking:home')
        else:
            messages.info(request,'User does not exist!')
            return redirect('SmartParking:signin')
    else:
        return render(request,'SmartParking/signin.html')

# @login_required
# def signout(request):
#     logout(request)
#     return redirect('Users:signin')

SmartParking/templates/SmartParking/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SMART PARKING - HOME</title>
    <link rel="stylesheet" href="{% static 'css/homestyle.css' %}">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
</head>
<body>
    <div class="container">
        <aside>
            <div class="top">
                <div class="logo">
                    <img src="{% static 'images/knust_logo.png' %}" alt="LOGO">
                    <h3><b>SMART</b><span class="danger">PARKING</span></h3>
                </div>
                <!-- <i class="material-icons">home</i>
<span class="material-icons">settings</span> -->
                <div class="close" id="close-btn">
                    <span class="material-icons">
                        close
                        </span>
                </div>
            </div>
            <div class="sidebar">
                <a href="{% url 'SmartParking:home' %}">
                    <span class="material-icons">home</span>
                    <h3>Home</h3>
                </a>
                <a href="">
                    <span class="material-icons">dashboard</span>
                    <h3>Dashboard</h3>
                </a>
                <a href="">
                    <span class="material-icons">location_on</span>
                    <h3>Map</h3>
                </a>
                <a href="">
                    <span class="material-icons">book_online</span>
                    <h3>Bookings</h3>
                </a>
                <a href="">
                    <span class="material-icons">payments</span>
                    <h3>Payments</h3>
                </a>
                <a href="">
                    <span class="material-icons">event_seat</span>
                    <h3>Reservation</h3>
                </a>
                <a href="">
                    <span class="material-icons">logout</span>
                    <h3>Logout</h3>
                </a>
            </div>
        </aside>
        <!-----------------------------END OF ASIDE SECTION------------------------->
        <main>
            <form action="">
                {% csrf_token %}
                <input type="text" name="search" id='search-input' placeholder="Where to...?">`
                <button id="search-button" type="submit">Search</button>
            </form>
            
            <div id="results">
                
                <h1>COLLEGE OF ENGINEERING</h1>
                
            </div>
            <div id="middle">
                    <div id="middle1">
                        <h1>PB</h1><br>
                        <h1 id="count1">5</h1>
                    </div>
                
                    <div id="middle2">
                        <h1>CENTRAL</h1><br>
                        <h1 id="count2">11</h1>
                    </div>
                
                
                    <div id="middle3">
                        <h1>LABS</h1><br>
                        <h1 id="count3">8</h1>
                    </div>

                    <!-- <div id="middle3">
                        <h1>Available Spaces</h1><br>
                    {% for space in spaces %} 
                        <h1>{space}</h1>
                    {% endfor %}
                    </div> -->
                
            </div>
           
        </main>
        <!----------------END OF MAIN------------->
        <div class="right">
            <div class="top">
                <button id="menu-btn">
                    <span class="material-icons">menu</span>
                </button>
                <div class="theme-toggler">
                    <span class="material-icons active">light_mode</span>
                    <span class="material-icons">dark_mode</span>
                </div>
                <div class="profile">
                    <div class="info">
                        <p>Hey</p>
                    </div>
                    <div class="profile-photo">
                        <img src="{% static 'images/knust_logo.png' %}" alt="profile-photo">
                    </div>

                </div>
            </div>
            <!--END OF TOP-->
            <div class="recent-update">
                <!-- <h2>RECENT UPDATES</h2> -->
            </div>
        </div>
    </div>

    <script>
        function updateCounts() {
            // Get the current counts
            var count1 = parseInt(document.getElementById("count1").innerText);
            var count2 = parseInt(document.getElementById("count2").innerText);
            var count3 = parseInt(document.getElementById("count3").innerText);
    
            // Update the counts
            document.getElementById("count1").innerText = count1 + 1;
            document.getElementById("count2").innerText = count2 + 1;
            document.getElementById("count3").innerText = count3 + 1;
        }
    
        // Update counts every 10 seconds
        setInterval(updateCounts, 10000);
    </script>
<script src="{% static 'js/homeScript.js'%}"></script>
</body>
</html>

SmartParking/templates/SmartParking/free_spaces.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Free Spaces</title>
</head>
<body>
    <h1>Free Spaces: {{ spaces }}</h1>
</body>
</html>

SmartParking/templates/SmartParking/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SMART PARKING - HOME</title>
    <link rel="stylesheet" href="{% static 'css/homestyle.css' %}">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
</head>
<body>
    <div class="container">
        <aside>
            <div class="top">
                <div class="logo">
                    <img src="{% static 'images/knust_logo.png' %}" alt="LOGO">
                    <h3><b>SMART</b><span class="danger">PARKING</span></h3>
                </div>
                <!-- <i class="material-icons">home</i>
<span class="material-icons">settings</span> -->
                <div class="close" id="close-btn">
                    <span class="material-icons">
                        close
                        </span>
                </div>
            </div>
            <div class="sidebar">
                <a href="{% url 'SmartParking:home' %}">
                    <span class="material-icons">home</span>
                    <h3>Home</h3>
                </a>
                <a href="">
                    <span class="material-icons">dashboard</span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{% url 'SmartParking:detail' %}">
                    <span class="material-icons">location_on</span>
                    <h3>Map</h3>
                </a>
                <a href="">
                    <span class="material-icons">book_online</span>
                    <h3>Bookings</h3>
                </a>
                <a href="">
                    <span class="material-icons">payments</span>
                    <h3>Payments</h3>
                </a>
                <a href="">
                    <span class="material-icons">event_seat</span>
                    <h3>Reservation</h3>
                </a>
                <a href="{% url 'SmartParking:signin' %}">
                    <span class="material-icons">logout</span>
                    <h3>Logout</h3>
                </a>
            </div>
        </aside>
        <!-----------------------------END OF ASIDE SECTION------------------------->
        <main>
            <form action="">
                {% csrf_token %}
                <input type="text" name="search" id='search-input' placeholder="Where to...?">`
                <button id="search-button" type="submit">Search</button>
            </form>
            <div class="parking_lots">
                <div class="parking_area1" onclick="window.location.href='{% url 'SmartParking:detail' %}'">
                    <div class="middle">
                        <a href="{% url 'SmartParking:detail' %}"></a><h2>COLLEGE OF ENGINEERING</h2></a>
                    </div>
                </div>
                <div class="parking_area2">
                    <div class="middle">
                        <h2>LIBRARY</h2>
                    </div>
                </div>
                <div class="parking_area3">
                    <div class="middle">
                        <h2>PHARMACY</h2>
                    </div>
                </div>
                <div class="parking_area4">
                    <div class="middle">
                        <h2>IMPACT AREA</h2>
                    </div>
                </div>
            </div>
        </main>
        <!----------------END OF MAIN------------->
        <div class="right">
            <div class="top">
                <button id="menu-btn">
                    <span class="material-icons">menu</span>
                </button>
                <div class="theme-toggler">
                    <span class="material-icons active">light_mode</span>
                    <span class="material-icons">dark_mode</span>
                </div>
                <div class="profile">
                    <div class="info">
                        <!-- <p>Hey</p> -->
                    </div>
                    <div class="profile-photo">
                        <img src="{% static 'images/knust_logo.png' %}" alt="profile-photo">
                    </div>

                </div>
            </div>
            <!--END OF TOP-->
            <div class="recent-update">
                <h2>RECENT UPDATES</h2>
                <div class="facts">
                    <ul>
                        <li>Smart parking systems can reduce parking search time by up to 50% and reduce traffic congestion by up to 30%.</li>
                        <li>According to a report by <span>MarketsandMarkets</span>,the global smart parking market is expected to grow from $5.25 billion in 2018 to 11.13 billion by 2024, at a CAGR of 16.4% during the forecast period.</li>
                        <li>A study by the International Parking Institute found that drivers spend an average of 17 hours per year searching for parking spots, resulting in wasted time, fuel, and increased traffic congestion.</li>
                        <li>A smart parking system can increase parking revenue by up to 20% through the implementation of dynamic pricing and optimization of parking space utilization, as reported by McKinsey & Company</li>
                    </ul>
                    
                </div>
                
            </div>
        </div>
    </div>
<script src="{% static 'js/homeScript.js'%}"></script>
</body>
</html>

SmartParking/templates/SmartParking/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LOGIN & REGISTER PAGE</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Crimson+Pro">
    
</head>

<body>
        <header>
            <h2 class="logo">LOGO</h2>
            <nav class="navigation">
                <a href="#">Home</a>
                <a href="#">About</a>
                <a href="#">Services</a>
                <a href="#">Contact</a>
                <button class="btnLogin-popup">Login</button>
            </nav>
        </header>

        <div class="wrapper">
            <div class="form-box login">
                <h2>Login</h2>
                <form action="#">
                    <div class="input-box">
                        <span class="icon"><ion-icon name="mail-outline"></ion-icon></span>
                        <input type="email" required>
                        <label class="label1" for="#">Email</label>
                    </div>
                    <div class="input-box">
                        <span class="icon"><ion-icon name="lock-closed-outline"></ion-icon></span>
                        <input type="password" required>
                        <label class="label2" for="#">Password</label>
                    </div>
                    <div class="remember-forget">
                        <label for="#" type="checkbox">
                            Remember me
                        </label>
                        <a href="#">Forgot Password?</a>
                    </div>
                    <button type="submit" class="btn">Login</button>
                    <div class="login-register">
                        <p>
                            Don't have an account? <a class="link-register" href="register">Register</a>
                        </p>
                    </div>
                </form>
            </div>
        </div>

    
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="script.js"></script>
</body>

</html>

SmartParking/templates/SmartParking/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LOGIN & REGISTER PAGE</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Crimson+Pro">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"> -->
    
</head>
<body>
        <header>
            <nav class="navigation">
                <a href="#">Home</a>
                <a href="#">About</a>
                <a href="#">Services</a>
                <a href="#">Contact</a>
                <button class="btnLogin-popup">Login</button>
            </nav>
        </header>

        <div class="wrapper">
            <span class="icon-close">
                <ion-icon name="close-outline"></ion-icon>
            </span>
            <div class="form-box login">
                <div class="logo">
                    <img src="{% static 'images/knust_logo.png' %}" alt="">
                </div>
                <h2>Login</h2>
                <form method="post" action="{% url 'SmartParking:signin' %}">
                    {% csrf_token %}
                    <div class="input-box">
                        <span class="icon"><ion-icon name="mail-outline"></ion-icon></span>
                        <input type="email" name="email" required>
                        <label class="label1" for="password">Email</label>
                    </div>
                    <div class="input-box">
                        <span class="icon"><ion-icon name="lock-closed-outline"></ion-icon></span>
                        <input type="password" name="password" required>
                        <label class="label2" for="password">Password</label>
                    </div>
                    <div class="remember-forget">
                        <label for="#"><input type="checkbox">
                            Remember me
                        </label>
                        <a href="#">Forgot Password?</a>
                    </div>
                    <button type="submit" class="btn">Login</button>
                    <div class="login-register">
                        <p>
                            Don't have an account? <a class="register-link" href="#">Register</a>
                        </p>
                    </div>
                </form>
            </div>

            <div class="form-box register">
                <div class="logo">
                    <img src="{% static 'images/knust_logo.png' %}" alt="">
                </div>
                <h2>Registration</h2>
                <form method="post" action="{% url 'SmartParking:signin' %}">
                    {% csrf_token %}
                    <div class="input-box">
                        <span class="icon"><ion-icon name="person-outline"></ion-icon></span>
                        <input type="text" name="username" required>
                        <label class="label3" for="">Username</label>
                    </div>
                    <div class="input-box">
                        <span class="icon"><ion-icon name="mail-outline"></ion-icon></span>
                        <input type="email" name="email" required>
                        <label class="label1" for="">Email</label>
                    </div>
                    <div class="input-box">
                        <span class="icon"><ion-icon name="lock-closed-outline"></ion-icon></span>
                        <input type="password" name="password" required>
                        <label class="label2" for="password">Password</label>
                    </div>
                    <div class="remember-forget">
                        <label for="#"><input type="checkbox">
                            I agree to the terms & conditions
                        </label>
                    </div>
                    <button type="submit" class="btn">Register</button>
                    <div class="login-register">
                        <p>
                            Already have an account? <a class="login-link" href="#">Login</a>
                        </p>
                    </div>
                </form>
            </div>
        </div>

    
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="{% static 'js/script.js'%}"></script>
</body>

</html>